### ISSUE TITLE
found a bug with example.c using "./db" instead of memory

### ISSUE THREAD

**Issue by sprappcom** [crossdb-org/crossdb#17]
**Describe the bug**
in example.c, replace with 
```
#include <crossdb.h>

int main (int argc, char **argv)
{
        xdb_res_t       *pRes;
        xdb_row_t       *pRow;

        xdb_conn_t      *pConn = xdb_open ("./db");

        // Create Table
        pRes = xdb_exec (pConn, "CREATE TABLE IF NOT EXISTS student (id INT PRIMARY KEY, name CHAR(16), age INT, class CHAR(16), score FLOAT, info CHAR(255))");

```
full code here:
https://pastebin.com/d6U8jFkp

**To Reproduce**
run
make example

then
exit and type
./example 

crash with error below:
```
./example 
[XDB Error] 9: 'CREATE TABLE student (  id               INT,  name             CHAR(16),  age              INT,  class            CHAR(16),  score            FLOAT,  info             CHAR(255),  PRIMARY KEY (id) XOID=0) XOID=0' ERROR 1 : Failed to create table 'student'
[XDB Error] 17: 'CREATE TABLE teacher (  id               INT,  name             CHAR(16),  age              INT,  info             CHAR(255),  PRIMARY KEY (id) XOID=0,  KEY         name_2 (name) XOID=1) XOID=1' ERROR 1 : Failed to create table 'teacher'
Segmentation fault (core dumped)
```

**Expected behavior**
doesnt work as expected with on disk.

**Desktop (please complete the following information):**
 - OS: ubuntu 24.04
 - Version latest

**Additional context**
on disk example cannot be ran twice.

**Comment by jcwangxp** [comment]
Please retest with 0.8.0
https://github.com/crossdb-org/crossdb/issues/15

**Comment by sprappcom** [comment]
ok thx for the prompt reply.

now cannot do make example as in the github issue.

**Comment by sprappcom** [comment]
i fixed it somehow. thx

**Comment by sprappcom** [comment]
also tested, the golang i've sent previously works now. how do u suggest i
provide the golang binding repo?

can u make one repo so i can add to it as officially endorsed by you etc?
