### ISSUE TITLE
CrossDB Rust Driver

### ISSUE THREAD

**Issue by wyhaya** [crossdb-org/crossdb#29]
Hi, can you create a `crossdb-org/crossdb-rs` repo? I would like to contribute to crossdb.
I have currently written some code that can run basic SQL queries, and it is here: [crossdb-rs](https://github.com/wyhaya/crossdb-rs)

---
Just noticed that @sprappcom in #24 wants to provide Rust bindings for crossdb; There may be some conflicts.

**Comment by jcwangxp** [comment]
I just created the repo and invite you as maintainer.
https://github.com/crossdb-org/crossdb-rust
His code is not ready and I don't know the progress. I think you can maintain this project together.

**Comment by kolinfluence** [comment]
@wyhaya u beat me to it. mine's almost completed tml. 
will use urs. :)

**Comment by kolinfluence** [comment]
@wyhaya i have issues with compiling and using urs. can u provide more information on how to use yours in the README.md?

**Comment by wyhaya** [comment]
@kolinfluence Currently, there are some warnings, but it can run normally on Linux and macOS. I haven't tested it on`Windows` yet. It's currently statically compiled, and you can check how to run the example in `.github/workflows/test.yml`.

**Comment by kolinfluence** [comment]
@wyhaya i just chked ur code, it's quite limited. i may use mine. i test if i can get it to work in 2 days. will update here

**Comment by kolinfluence** [comment]
@jcwangxp i'll continue with mine. my code is more comprehensive. his code works for now but it's very limited. if i cant get it to work in 2 days, will update here again.

**Comment by jcwangxp** [comment]
@kolinfluence , I've invited you too. you can work together.
in addition, i added 2 functions which will make the binging easy.
```c
xdb_type_t
xdb_column_type (uint64_t meta, uint16_t iCol);

const char* 
xdb_column_name (uint64_t meta, uint16_t iCol);
```

**Comment by kolinfluence** [comment]
@wyhaya although mine's more comprehensive, i'm having some issues with making everything come together.
1. urs seemed to work for now so will use and improve upon urs.
2. can you figure out how to fix the warnings? it's quite annoying.

**Comment by jcwangxp** [comment]
I've fixed crossdb comping warnings, please pull latest code.
