### ISSUE TITLE
WAL now! thx for the varchar. i really tot sunday will be done. impressive.

### ISSUE THREAD

**Issue by kolinfluence** [crossdb-org/crossdb#31]
when's the eta for wal feature?

will help do the var test.

what u going to do next?

now is "production ok".

wal will make this production ready.

**Comment by jcwangxp** [comment]
I'm working on wal already, maybe 1 week or more.

**Comment by kolinfluence** [comment]
@jcwangxp WAL is completed? that's amazing.

is there any ways i can test how to crash it etc and recover etc?

where's the section to "interface" with wal? i'm thinking replication next and would like to look into it and see if i can maybe use it for replication

**Comment by jcwangxp** [comment]
You can do transaction test and kill the process or power cycle, then open the DB and check data consistency.
Current WAL is for high performance transaction ACID, and can't be used for replication.
I'm developing client server feature, then will develop replication mechanism.
