### ISSUE TITLE
CrossDB bindings for JavaScript (Node.js)

### ISSUE THREAD

**Issue by damartripamungkas** [crossdb-org/crossdb#32]
Hi,
I am interested in using CrossDB with JavaScript (Node.js) and was wondering if there are any existing bindings or plans to support Node.js. If not, would it be possible to add this feature in the future? Any information or guidance on how to implement it would also be appreciated.

Thanks!

**Comment by jcwangxp** [comment]
Sorry, I'm not familiar with js. Could you refer sqlite js and implement the binding? 
You can refer following bindings also.
https://github.com/crossdb-org/crossdb-cpp/blob/main/crossdb.hpp
https://github.com/crossdb-org/crossdb-python/blob/main/crossdb.py
https://github.com/crossdb-org/crossdb-go/blob/main/crossdb.go
If you're ready, I can create a reop and invite as maintainer.

**Comment by efremropelato** [comment]
Now that the crossdb are working for me too :-)
If there’s a chance, I can handle the Node.js "driver".

**Comment by jcwangxp** [comment]
@efremropelato you're welcome to contribute the node.js driver.

**Comment by efremropelato** [comment]
First release is ready: https://github.com/efremropelato/crossdb-js

**Comment by efremropelato** [comment]
@jcwangxp 
Nodejs driver is ready.
I improved the example like your with C ([example.c](https://github.com/crossdb-org/crossdb/blob/main/examples/c/example.c)).

Missing the "Multi-Statements" feature

**Comment by jcwangxp** [comment]
@efremropelato thank you so much, I've created https://github.com/crossdb-org/crossdb-nodejs and invited you as maintainer.
