### ISSUE TITLE
optimization for even more extreme efficiency

### ISSUE THREAD

**Issue by kolinfluence** [crossdb-org/crossdb#33]
i havent really check the code yet but i was thinking your sql prepared statement query, not sure if it can be further optimized for even more extreme performance?

somehow i feel there are opportunities for more performance like 40-60% more.

maybe a crossdbx version for the most extreme efficiency.

it's doable. hope u can think about this for such implementation.

**Comment by jcwangxp** [comment]
If you need extremely speed, you should use hashmap. The language native hashmap is slow, you need to find 3rd library, for example the abseil hashmap.
General RDBMS can't be that fast.
