### ISSUE TITLE
can u develop one called crosskv specifically for use in kv like redis use?

### ISSUE THREAD

**Issue by kolinfluence** [crossdb-org/crossdb#34]
crosskv as titled

**Comment by jcwangxp** [comment]
There're many [kv DBs](https://db-engines.com/en/ranking/key-value+store).
and you can just create one table with 2 cols (key VARCHAR(65535), value VARCHAR(65535)) to use as kv db. Future will support long text type.

**Comment by kolinfluence** [comment]
@jcwangxp yes i know there are plenty kv dbs but u can make one just for this faster with less overhead. do mention if u can do this or will do so. maybe in 1 years' time or something

**Comment by jcwangxp** [comment]
sorry, kv db is not in my plan now, you can try lmdb which is small and fast.
