### ISSUE TITLE
Error to build and/or install - MacOS Sequoia

### ISSUE THREAD

**Issue by efremropelato** [crossdb-org/crossdb#36]
**Describe the bug**
Warning during build process, and /usr/local/lib/ no such file or directory

**To Reproduce**
exec `make build` and `make installmac`

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia 15.1
 - GNU Make 3.81
 - Apple clang version 16.0.0 (clang-1600.0.26.4) 

**screenshot**
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/83faa4e0-172e-40bb-ad0e-14ee40bcfd0a">
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/476c72ff-7716-4817-b10d-081319d75451">

**Comment by jcwangxp** [comment]
please pull and try again.

**Comment by efremropelato** [comment]
Build work, but not a connectors
![image](https://github.com/user-attachments/assets/bb27663f-794d-4cef-8249-4c526f77ce9f)
![image](https://github.com/user-attachments/assets/8d22e724-beca-42e3-989b-d546baaa8fbd)
