### ISSUE TITLE
MacOs Sequoia - Build work, but not a connectors.

### ISSUE THREAD

**Issue by efremropelato** [crossdb-org/crossdb#38]
Describe the bug
Build work, but not a connectors.

To Reproduce
exec `make build` and `make install`

Desktop:

OS: MacOS Sequoia 15.1
GNU Make 3.81
Apple clang version 16.0.0 (clang-1600.0.26.4)

> same error with golang example

![image](https://github.com/user-attachments/assets/bb27663f-794d-4cef-8249-4c526f77ce9f)
![image](https://github.com/user-attachments/assets/8d22e724-beca-42e3-989b-d546baaa8fbd)

_Originally posted by @efremropelato in https://github.com/crossdb-org/crossdb/issues/36#issuecomment-2475583489_

**Comment by efremropelato** [comment]
I try with `ifeq ($(shell sh -c 'uname 2>/dev/null || echo Unknown'), Darwin)`

<img width="724" alt="image" src="https://github.com/user-attachments/assets/5cd6a79f-0584-446f-870b-40ff58c2e77d">

work fine, but

<img width="654" alt="image" src="https://github.com/user-attachments/assets/977fbd40-d65e-4527-a7df-48570d500273">

**Comment by jcwangxp** [comment]
thanks, please uninstall then pull and try install again.
