### ISSUE TITLE
MacOs Sequoia -  make example doesn't work

### ISSUE THREAD

**Issue by efremropelato** [crossdb-org/crossdb#39]
Nothing has changed 😭

![image](https://github.com/user-attachments/assets/435373f4-5d42-49f8-b4ee-f46e710e8a89)

Current commit reference
![Screenshot 2024-11-15 alle 11 33 44](https://github.com/user-attachments/assets/0982cfe0-df14-4ffe-baeb-32356e3bcaea)

_Originally posted by @efremropelato in https://github.com/crossdb-org/crossdb/issues/38#issuecomment-2478527485_

**Comment by jcwangxp** [comment]
Could you copy the full link error which is truncated and there is link search path.
And could you copy the `libcrossdb.so` to `/usr/lib/`, then have a try, maybe `/usr/local/lib` is not in the default search path.

**Comment by jcwangxp** [comment]
This article says: The standard locations for dynamic libraries are ~/lib, /usr/local/lib, and /usr/lib.
https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html
And the /usr/local/lib can work in my system, could you try to change the suffix from .so to .dylib and have a try?
```
	$(CC) -o build/libcrossdb.dylib -dynamiclib -lpthread -O2 src/crossdb.c
	install -c build/libcrossdb.dylib /usr/local/lib/
```
it still doesn't work, change to `install -c build/libcrossdb.dylib /usr/lib/` and try again.

**Comment by jcwangxp** [comment]
I just updated the makefile, please try again and paste the full link error if still doesn't work. And is there any file in /usr/local/lib?

**Comment by efremropelato** [comment]
Test with `*.dylib` extention:
![image](https://github.com/user-attachments/assets/af391413-e203-4c19-8f52-ec1f77ee808e)

and with `/usr/lib` path:
![Screenshot 2024-11-15 alle 13 33 38](https://github.com/user-attachments/assets/7f9975ca-8f7d-4f05-8860-0133eb3518f5)

`*.dylib` and `/usr/lib` path together return the same `Operation not permitted` error

**Comment by efremropelato** [comment]
Always looking for lib in `build/` path. 

After pull:
![image](https://github.com/user-attachments/assets/67e784d3-b8c9-4794-b767-3a9f2ef117bd)

**Comment by jcwangxp** [comment]
I just changed the makefile, and there's no build/ folder now (not sure this is the issue), and in my system, if I remove /usr/lib/local/libcrossdb.dylib, it'll show following errors

dyld[1107]: Library not loaded: libcrossdb.dylib
  Referenced from: <B7244393-55CD-31D6-8EF1-FFB34287BD5B> /Users/user/crossdb/examples/c/example.bin
  Reason: tried: 'libcrossdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcrossdb.dylib' (no such file), 'libcrossdb.dylib' (no such file), '/usr/local/lib/libcrossdb.dylib' (no such file), '/usr/lib/libcrossdb.dylib' (no such file, not in dyld cache), '/Users/user/crossdb/examples/c/libcrossdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/crossdb/examples/c/libcrossdb.dylib' (no such file), '/Users/user/crossdb/examples/c/libcrossdb.dylib' (no such file), '/usr/local/lib/libcrossdb.dylib' (no such file), '/usr/lib/libcrossdb.dylib' (no such file, not in dyld cache)

If this still doesn't work, could your try following commands
```
cd examples/c
gcc example.c /usr/local/lib/libcrossdb.dylib
./a.out
```

```
user@users-iMac-Pro c % clang -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jcwangxp** [comment]
I upgraded to clang-16 and can reproduce the same issue. This is because the linker & loader behavior change in clang-16.
I've fixed the issue and please try again.

**Comment by efremropelato** [comment]
WORK!!!!!

![image](https://github.com/user-attachments/assets/d65c877d-fd86-46f8-89f2-da73ee27bb48)
