### ISSUE TITLE
Price estimate?

### ISSUE THREAD

**Issue by FatBrownDog** [crossdb-org/CrossDB#7]
I see your recent web-page:
https://crossdb.org/products/price/

Q1. If I have an app, if computer have 64-cores. so will process be limited to 1 core?
Is there a demo, where you can show, for example, if computer have 8 cores, all cores will be used to process data?

Q2. How does multiple EXEs (multiple apps) access 1 database? What price will that be? US$100 x 2 ... ?
How is this cross-db licensed, is it licensed per app?,  
Can you explain?

Example.
App1 open database.
App2 opens database.
App1 writes to database.
App2... how does it get latest data?

Q3. How does license work? 
If I buy bronze, what duration of support or updates?
2 years?, life-time, 1 year?

Q4. Is there price beyond diamond, if obtain sources?
How does it work? Is it licensed per user or per app, or some DB processing restriction... ?

**Comment by jcwangxp** [comment]
> I see your recent web-page:
> https://crossdb.org/products/price/

[A] This page is not open and only a draft idea, so don't take it seriously.

> Q1. If I have an app, if computer have 64-cores. so will process be limited to 1 core?
> Is there a demo, where you can show, for example, if computer have 8 cores, all cores will be used to process data?

[A] CrossDB is thread-safe, so you can create many threads to access the DB. 
In addition CrossDB has special parallel lock, when many threads access same table and most operations are read, then the QPS can scale with cores, however with traditional read-write lock, the QPS will reduce dramatically with cores number. But this is not delivered yet, will be ready soon.

> Q2. How does multiple EXEs (multiple apps) access 1 database? What price will that be? US$100 x 2 ... ?
> How is this cross-db licensed, is it licensed per app?,
> Can you explain?
> 
> Example.
> App1 open database.
> App2 opens database.
> App1 writes to database.
> App2... how does it get latest data?

[A] You can create a shared DB like this: cross_dbCreate (&hDb, "db_data/tutorial", CROSS_SHARED);
After App1 writes to DB, App2 can read the data immediately, but there is no notification mechanism. 
If DB is not too big, there is another option to use future PUBSUB mechanism, App2 has its own DB and it can subscribe the DB in App1. App2 can register hook for its own DB, when App1 changes DB, App2's hook will be called for insert/update/delete.

> Q3. How does license work?
> If I buy bronze, what duration of support or updates?
> 2 years?, life-time, 1 year?

[A] For the binary library, it's free to use. If need support, may charge by project/year.

> Q4. Is there price beyond diamond, if obtain sources?
> How does it work? Is it licensed per user or per app, or some DB processing restriction... ?

[A] If you get source code, you're free to use inside your company. I've sent you mail, if you didn't get it, please check the junk box.
