### ISSUE TITLE
The future of the CrossDB.

### ISSUE THREAD

**Issue by nop4LOL** [crossdb-org/CrossDB#8]
As a new non-open-source database product, why impose restrictions and charge for it? I suggest not charging because once you have a large user base and community, your traffic will increase, and the money will naturally come in without relying on selling the product itself. What do you think? For example, I'm a new user, and I came across CrossDB on Google, but when I found out there are limitations and charges, I instantly lost interest in using it.

**Comment by nop4LOL** [comment]
Perhaps you are a proud programmer, thinking that your product is the best in the universe. But all of that is just self-fulfillment in your mind. Without the recognition and usage from a user base, what's the point of having your project sitting idle on a hard drive? In 5 years, 10 years, even Windows and Linux systems may have been iterated out. It is crucial to launch the right product at the right time, gather a large user base, enhance your own reputation and value. These are the most important factors.

**Comment by paulocoghi** [comment]
Maybe I haven't looked properly, but it seems to me that CrossDB is open source, Apache 2.0 License, and there are no restrictions about commercial usage.

Could you share where you read that CrossDB isn't open source and there are limitations and charges? (sincere question)

**Comment by jcwangxp** [comment]
@nop4LOL thanks for your suggestion.
@paulocoghi thanks for your reply.
Current CrossDB is only designed for C/C++ which is limited in scenarios, so I'm re-designing CrossDB to make it a more standard SQL RDBMS and can support more languages, Client/Server mode and replication in future.
About source code license, I plan to use AGPL for open source, and MIT for subscription.

**Comment by dongyangfu** [comment]
Hello, big shot
I heard that Crossdb is about to open up. Can you send me the current source code for worship and learning?

**Comment by jcwangxp** [comment]
I plan to release some code end of this month.
