### ISSUE TITLE
同一个字段如何多个条件查询

### ISSUE THREAD

**Issue by xmwenfeng** [crossdb-org/CrossDB#9]
同一个字段如何多个条件查询
比如 prefix<10  prefix>5
比如 prefix<,prefix>

**Comment by jcwangxp** [comment]
那个pMatRow传入一个数组(目前只支持2个)，比如
route_t rt[2];
rt[0].prefix=5;
rt[1].prefix=10;
pMatFlds: "prefix>,prefix<"
这个项目目前正在重新开发，后面会是标准的SQL关系数据库，支持多种语言，并且开源，敬请期待...

**Comment by xmwenfeng** [comment]
重新开发的项目,大概什么时候发布呢？

**Comment by jcwangxp** [comment]
正在紧张开发，计划这个月底发个简单版本
